language: python
install:
  - pip install tox
script:
  - tox
env:
  - TOXENV=pep8
  - TOXENV=pypy
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=node
  - TOXENV=coveralls

before_install:
  - "[[ \"$TOXENV\" == \"node\" ]] && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 || true"
  - "[[ \"$TOXENV\" == \"node\" ]] && sudo apt-get install chromium || true"

before_script:
  - "[[ \"$TOXENV\" == \"node\" ]] && export CHROME_BIN=chromium || true"
  - "[[ \"$TOXENV\" == \"node\" ]] && export DISPLAY=:99.0 || true"
  - "[[ \"$TOXENV\" == \"node\" ]] && sh -e /etc/init.d/xvfb start || true"
  - "[[ \"$TOXENV\" == \"node\" ]] && sleep 3 || true"

after_success:
  - "[[ \"$TOXENV\" == \"coveralls\" ]] && coveralls || true"
